version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: karigo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: karigo
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - karigo_network

  redis:
    image: redis:7-alpine
    container_name: karigo_redis
    restart: unless-stopped
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    ports:
      - "6381:6379"
    volumes:
      - redisdata:/data
    networks:
      - karigo_network

volumes:
  pgdata:
  redisdata:

networks:
  karigo_network: